name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v4

            - name: List & Read file
              run: |
                    echo "My first Github Actions Job" 
                    ls -ltra 
                    cat README.md
            
            # - name: List files
            #   run: ls

            # - name: Read File
            #   run: cat README.md
    