name: Generate ASCII artwork

on:
    push

jobs:
    build_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: Install Cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
            
      - name: Sleep for 30 seconds
        run: sleep 10

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 seconds
          run: sleep 10
    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu_latest
        steps:
        - name: Read file
          run: echo "Deploying......"    